version: '3.8'

services:
  uber-server:
    build:
      context: ./server
    command: python manage.py runserver 0.0.0.0:8000
    container_name: uber-server
    depends_on:
      - uber-redis
      - uber-database
    environment:
      - PGDATABASE=uber
      - PGUSER=uber
      - PGPASSWORD=uber
      - PGHOST=uber-database
      - REDIS_URL=redis://uber-redis:6379/0
    ports:
      - 8003:8000
    volumes:
      - ./server:/usr/src/app


  uber-redis:
    container_name: uber-redis
    image: redis:6-alpine
  
  uber-database:
    container_name: uber-database
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=uber
      - POSTGRES_PASSWORD=uber
    expose:
      - 5432
    volumes:
      - uber-database:/var/lib/postgresql/data
    
  uber-client:
    build:
      context: ./client
    command: npm start
    container_name: uber-client
    depends_on:
      - uber-server
    ports:
      - 3001:3000
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  uber-database: